---
- name: Lookup MATLAB license manager
  stat: "path={{ u_matlab_lmdown }}"
  register: __lmdown

- name: Shutdown the MATLAB license manager
  shell: "{{ u_matlab_lmdown }}"
  when: __lmdown.stat.exists is defined and __lmdown.stat.exists

- name: Remove license manager files
  shell: "rm /var/tmp/lm_TMW*"
  ignore_errors: yes
  when: __lmdown.stat.exists is defined and __lmdown.stat.exists

- name: Remove MATLAB
  file: "dest={{ u_matlab_root }} state=absent"

- name: Remove symlinks to MATLAB binaries
  file: "dest={{ item }} state=absent"
  with_items: "{{ u_matlab_bin_links }}"
